apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: azure-minecraft
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: azure-minecraft
    spec:
      containers:
      - name: azure-minecraft
        image: openhack/minecraft-server:2.0 
        env:
        - name: EULA
          value: "TRUE"
        volumeMounts:
        - mountPath: "/data"
          name: volume
        ports:
        - name: minecraft
          containerPort: 25565
        - name: rcon
          containerPort: 25575
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: azurefile
---
apiVersion: v1
kind: Service
metadata:
  name: azure-minecraft
spec:
  type: LoadBalancer
  ports:
  - port: 25565
    targetPort: 25565
    name: minecraft
  - port: 25575
    targetPort: 25575
    name: rcon
  selector:
    app: azure-minecraft
